### ISSUE TITLE
implement Offline mode with ServiceWorkers

### ISSUE THREAD

**Issue by entone** [NationalAssociationOfRealtors/SmartHomeChecklist#15]
a good starting point, https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-3-offline-support-and-network-resilience-c84db889162c

**Comment by johnosullivan** [comment]
@entone, working service worker enhancement on offline-mode branch. Uses Google's sw-precache library (https://github.com/GoogleChrome/sw-precache). Updates are made to index.html. Once a build is created, a build script has to be ran to generate the custom service worker script for the current build.
