### ISSUE TITLE
Look at left alignment of "Designed and built...". See attached grab. (iphone 6, Safari and Chrome).

### ISSUE THREAD

**Issue by johnosullivan** [NationalAssociationOfRealtors/SmartHomeChecklist#31]
![iphone6](https://user-images.githubusercontent.com/19661156/27541639-3d679f1a-5a4a-11e7-903f-7e1dd4a0b0e4.PNG)

**Comment by jsullivancrt** [comment]
Can't reproduce; only an issue on iPhone6.
